[package]
name = "framed-postcard"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
crc = "3.4"
defmt = "1.0"
thiserror = "2.0"
postcard = "1.1"
corncobs = "0.1"